name: Simple CI

on:
  push:
    branches:
      - master
      - develop
      - feature-login
      - feature-footer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Repository Files
        run: ls -la

      - name: Display Success Message
        run: echo "GitHub Actions workflow executed successfully!"